#!/bin/bash

pos=$(dirname "$0")

method=$1
path=$2
data=$3

if [ $method = "help" ]; then
    echo "use: test methode apiPath dataFile"
else
    if test $file; then
        curl -d "@${file}" -H "Content-Type: application/json" -X ${method} "127.0.0.1:3000$path"
    fi
fi
