version: "1.0"
services:
    server:
        build: .
        container_name: info701_server
        volumes:
            - "./src/:/mnt/"
        ports:
            - 3000:3000
        entrypoint: ['nodemon', 'server.js']
        depends_on:
            - info701_mysql
        links:
            - info701_neo4j
            - info701_mysql
        networks:
            - info701

    mysql:
        image: mysql
        container_name: info701_mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./.mysql-data/db:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: users
        networks:
            - info701

networks:
    info701:
        driver: bridge

